name: CI Pipeline

on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    needs: security-gates
    runs-on: ubuntu-latest

    steps:
      - name: Gate 1 — Scan de segredos (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar testes automatizados
        run: pytest -v

      - name: Build da imagem Docker
        run: docker build -t devops-lab-00:${{ github.sha }} .

      - name: Gate 2 — SAST (Bandit)
        run: bandit -r . -x ./venv -ll
